
# Ajouter le dépôt GitLab
helm repo add gitlab https://charts.gitlab.io/

# Mettre à jour les dépôts
helm repo update

# Vérifier les charts disponibles
helm search repo gitlab

# Créer un namespace (s'il n'existe pas déjà)
kubectl create namespace gitlab

# Installer GitLab avec Helm
helm install gitlab gitlab/gitlab --namespace gitlab -f values.yaml

apiVersion: v1
kind: Service
metadata:
  name: svc-app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
